### PR TITLE
Pawn package definition

### PR DESCRIPTION
**Pull request by Southclaws**
Since [sampctl](https://github.com/Southclaws/sampctl) is getting to the point where it's production-ready, I'm encouraging people to start using it while developing libraries as it should make the process of testing and developing a lot smoother. It's designed so you don't need a `pawn.json`/`pawn.yaml` ("Pawn-Package Definition" file) in every repo, but having it there really helps with dependency management! These changes are purely additive and do not change your code or scripting style in any way, you don't need to use sampctl yourself but I encourage you to [give it a try](https://github.com/Southclaws/sampctl/wiki#installation)!

- added sampctl package files for version control, so a user could now simply run `sampctl package install Misiur/YSI-Includes` to start using this library in their gamemode which would automatically pull in `Zeex/amx_assembly`.

### CODE REVIEW

**Comment by Y-Less** [comment]
It would be very helpful if you could also do this for the [Branch_JIT](https://github.com/Misiur/YSI-Includes/tree/Branch_JIT) branch, probably more useful since it has far more dependencies.  Thanks.

**Comment by Southclaws** [comment]
Yes I've been meaning to check out the JIT work actually, I'll do that.

However, branches actually haven't crossed my mind while working on sampctl so there's currently no way to say "I want this specific branch of this dependency" yet so I'll get working on some unit tests for branches (and probably use the YSI JIT Branch as a testbed), thanks!

**Comment by Y-Less** [comment]
I more meant can you commit this file to that branch, not can you make a dependency on that branch.  But I guess both are useful.

**Comment by Y-Less** [comment]
Also, does something depend on YSI currently work, since the default branch is not master?  Or does the fact that it is set as default suffice?

**Comment by Southclaws** [comment]
Yeah I've recently been going through all my old releases and "packaging" them to test the tool out and YSI all works fine, seems the default branch is picked up implicitly by the Git library I'm using.

**Pull request merged**
