### PR TITLE
Added `OnClientCheckResponse` & `SendClientCheck`.

### PR DESCRIPTION
**Pull request by DEntis-T**
Forwarded `OnClientCheckResponse` and added native `SendClientCheck`.

### CODE REVIEW

**Comment by DEntis-T** [comment]
These two aren't in my a-samp.inc

**Comment by DEntis-T** [comment]
I get undefined-symbol and function lacks forward declaration errors.

**Comment by DobbysGamertag** [comment]
> These two aren't in my a-samp.inc

No but they're in the std-lib, [look](https://github.com/pawn-lang/samp-stdlib/blob/master/a_samp.inc#L3190)

**Comment by Y-Less** [comment]
They aren't in the default includes, so should maybe be in here.  However, in that case:

a. The `public` should match the original definition, which the `forward` doesn't.

b. The `native` should go with the other custom natives in y_natives, and follow their naming sceheme.

**Comment by DEntis-T** [comment]
Useless PR

**Pull request closed without merging**
