### PR TITLE
Add MySQL ORM functions for y_inline

### PR DESCRIPTION
**Pull request by AGraber**
Since I noticed basic MySQL query functions were given an inline counterpart I though that the ORM ones may have one as well.

### CODE REVIEW

**Comment by Y-Less** [comment]
I've not decided on a good naming scheme for inline equivalents yet (the other functions in that file don't use `_Inline` though). Any ideas?

**Comment by Y-Less** [comment]
Also, that was the file I thought contained Inline_FromCallback, but apparently not any more.

**Comment by Y-Less** [comment]
Sorry, just saw your "correct naming" commit was removing the _, not adding it, ignore my first reply.

**Comment by AGraber** [comment]
I made a different PR just in case you got any special plan for that callback; one can't be too careful.

**Pull request merged**
