### PR TITLE
Several changes.

### PR DESCRIPTION
**Pull request by Y-Less**
- Fixed recursive `va_CallRemoteFunction`.
- Fixed several y_iterate options.
- Added `Iter_Index`.

Just look at the commits really...  These are actually several commits from the last few months on my other branch that I spent some time cherry-picking in to this branch instead.

### CODE REVIEW

**Comment by Vasily-X** [comment]
@Y-Less what's the best way to break a foreach loop? Does the standard `break` work? Or something like:

```
foreach(new x : my_Iterator)
{
    if(condition)
    {
        x = Iter_End(my_Iterator);
    }
}
```
Thank you.

**Comment by Southclaws** [comment]
foreach is just a regular for loop under the hood, break works fine.

**Comment by Y-Less** [comment]
Forgot I could aprove pull requests (though I don't like sproving my own and instantly regretted it - it is always good to have someone else at least glance at it).

**Comment by Y-Less** [comment]
This commit also makes some parts of YSI JIT-compatable, but that wasn't the main aim.  I'm still working on that (to be honest, I've been at the same point for months - I've completed everything except y_inline code-gen, the scanning is complete but the last part is HARD and I don't want to tackle it (even though it will probably be simpler than I think once I convince myself to start)), these were just some other fixes that happen to have some JIT-compatable changes mixed in.

**Comment by Y-Less** [comment]
Yet another thing I forgot to mention was in this commit (I really should have been more careful) is y_profile, which adds y_testing-like functions:

```pawn
Profile:CountTo10()
{
    for (new i = 0; i != 10; ++i) {}
}
```

Will produce some nice statistics on how long that code takes - averages over multiple runs etc.  Saves all the faffing about with timers and tick counts and many runs.  It is based on the profiling macros that have been in y_utils for a long time, but even more wrapped up.  I think you can also specify a number of runs:

```pawn
Profile:CountTo5[10000]()
{
    for (new i = 0; i != 5; ++i) {}
}
```

The code is somewhat equivalent to:

```pawn
for (new a = 0; a != TIMING_ITERATIONS; ++a)
{
    new start = GetTickCount();
    for (new b = 0; b != ???; ++b)
    {
        // Code
    }
    new time = GetTickCount() - start;
}
```

As I say, the main code is here:

https://github.com/Misiur/YSI-Includes/blob/4f1fd377d5bb9e761fd2a5a328421409a979d413/YSI_Core/y_utils.inc#L163-L208

So it runs the code multiple times, records that time, then repeats the whole thing 10 times (by default) to take averages.

@irinel1996 : You can also use `continue` inside `foreaach`.

**Pull request merged**
