### PR TITLE
Changed Vehicle_Speed function

### PR DESCRIPTION
**Pull request by lPauI**
Hi. The better of Vehicle_Speed function is without Vz because this help developers to improves your anti-cheat and multiplied with 170, not with 136.666667.

### CODE REVIEW

**Comment by Y-Less** [comment]
There's a lot of debate over the correct value.  What's your source on 170, because I don't want to change it to another value that might be just as wrong.

**Comment by Y-Less** [comment]
And why would you not want z velocity?

**Comment by lPauI** [comment]
I talked with you on discord about the value and you said that 170 is correct. And I don't wanna z on velocity because help developers to make an anti cheat for vehicle speed hacks

**Comment by Y-Less** [comment]
I didn't say 170 is correct, I asked if you had evidence for one value over another?  I still don't understand why you wouldn't want Z included in the calculation.  The vertical component of movement is still a part of the speed.

**Pull request closed without merging**
