### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by Misiur**
Dialog with normal string instead of y_text string as a body. Might need to add to documentation

### CODE REVIEW

**Review by Y-Less — COMMENTED** [review]
I'm still confused by how this is different to the normal one - `Text_DialogBox` already does formatting.

**Comment by Y-Less** [comment]
Actually, I looked closer and the only difference seems to be that this one doesn't do any formatting, which seems odd given its name and prototype.

**Comment by Misiur** [comment]
So, I use it for dynamic lists to not have to manually `Text_Format` title and the buttons. I think that's because `%s` parameter has 128 chars limit or something like that, I'll have to double check that

**Comment by Misiur** [comment]
By `Formatted` in name I think of it as of "already formatted" or something like that

**Comment by Y-Less** [comment]
As far as I can see, you pass a string in directly for the main body, but still use text set entries for the title and buttons.  Yes?

**Comment by Misiur** [comment]
Exactly

**Comment by Y-Less** [comment]
Except you can already do that...

**Comment by Misiur** [comment]
Oh shit! I was only looking at (macro) params, didn't bother to look at the source code...

**Comment by Y-Less** [comment]
Yeah, the macros don't support it, so would need updating.  Actually, for some reason the macros let you do `library->section[name]` and `"library->section[name]"`, can probably get rid of the second version.

**Pull request closed without merging**
