### PR TITLE
Fixed AMX_GetNameSuffix

### LINKED ISSUE #191: y_text: Text not Found
I followed up everything as instructed but for some reason y_text can't read the text and, to top it, stucks in some kind of infinite loop that freezes the server, only option to pkill -9 samp03svr.

Directory structure:
```
- gamemodes
|
|- TDM.amx
- scriptfiles
|
|- YSI
 |- mensajes_LANG_DATA.yml
 |- text
  |
  |- mensajes.ES
  |- mensajes.EN
```

TDM.pwn: https://pastebin.com/6FWCBDnx **(Updated)**
mensajes.ES: https://pastebin.com/rCPVdrNt
mensajes.EN: https://pastebin.com/jcxZb3h1

Server Log:
```
[15:40:41] Text_Render: Loop: p = 14, llen = 49, output = "Text Not Found"
[15:40:41] Text_Render: Final render?
[15:40:41] Text_Render: Yes!
[15:40:41] Text_Render: p = 14, output = "Text Not Found"
[15:40:41] 00000054 = T
[15:40:41] 00000065 = e
[15:40:41] 00000078 = x
[15:40:41] 00000074 = t
[15:40:41] 00000020 =  
[15:40:41] 0000004E = N
[15:40:41] 0000006F = o
[15:40:41] 00000074 = t
[15:40:41] 00000020 =  
[15:40:41] 00000046 = F
[15:40:41] 0000006F = o
[15:40:41] 00000075 = u
[15:40:41] 0000006E = n
[15:40:41] 00000064 = d
[15:40:41] Text_Render end
[15:40:41] Text_GetText: loop1 mode_text:all 0 -1 mode_text:all 109
```

Last line is an infinite loop that repeats like a million times. I double checked everything and nothing is missing. Using Ubuntu 16.04 64-bit, whole folder with chmod 777.

### PR DESCRIPTION
**Pull request by Misiur**
Closes #191 

That was silly bughunt, but works so whatever

### CODE REVIEW

**Review by Y-Less — APPROVED** [review]
Looks fine.

**Review by Y-Less — CHANGES_REQUESTED** [review]
Actually, I just noticed that this now has a double increment in the loop.  What bug was this fixing?  I trust you, but I can't accurately review without a bug report or test case (a test would be nice in general actually).

**Comment by Misiur** [comment]
https://github.com/Misiur/YSI-Includes/issues/191#issuecomment-323037179 here's my investigation - basically it skipped half of the publics, so it might have worked half the time

**Comment by Misiur** [comment]
As for test cases - do you think rearranging y_amx from a single file into your standard folder/(impl|tests) format is good?

**Comment by Y-Less** [comment]
Ahh, I misread your pull request - I thought you were adding the second increment and wasn't sure why it was needed. But you were removing it, which makes sense because there shouldn't be two - none of the other similar functions have two. Thanks.

And ideally I'd like all the libraries in the impl/test form, since tests are good, but don't bother if you don't want for this one, the fix makes sense to me now.

**Pull request merged**
