### PR TITLE
y_hooks array parameters support

### PR DESCRIPTION
**Pull request by Yiin**
```
#define ALS_DO_ArrayTest<%0> %0<ArrayTest,aa>(array:arr1[E_TEST_DATA], end_array:arr2[E_TEST_DATA])

enum E_TEST_DATA {
	E_DATA_INT,
	Float:E_DATA_FLOAT,
	E_DATA_STRING[32]
};

hook OnArrayTest(arr1[E_TEST_DATA], arr2[E_TEST_DATA]) {
```

### CODE REVIEW

**Comment by Yiin** [comment]
Actually I'm not sure why I wrote "aa" for parameter types in ALS_DO_ define, but it seems to be working fine for some reason.

**Comment by Y-Less** [comment]
This is good, but it isn't y_hooks support - y_hooks and y_als are separate, the latter was created to simplify making ALS hooks of standard callbacks, but was created before y_hooks and has now been almost entirely superceeded.

If you're wondering why y_hooks seems to work with "aa" instead of just "a" that's the reason - the systems used to be linked, but are now not, and y_hooks already supports any data type (except references, I don't even know if you can use them in public functions, but if so that would be an excellent thing to support).

**Comment by Yiin** [comment]
> I don't even know if you can use them in public functions

Not sure what you exactly have in mind, but when we're simply calling public function, variables are referenced properly. https://gist.github.com/Yiin-/a72e2c79566e56fc117f27aaa9bf8015

Edit @ 2016-12-28
Slice's version of CallLocalFunction that Y-Less mentions below: https://gist.github.com/Yiin-/097a78e889afa0d381a18c3f38ce71a1

**Comment by Y-Less** [comment]
Well that answers that...  I know Slice wrote a version of `CallLocalFunction` that handled them, but we are getting way off topic.  Your patch is fine for what it does, so I'll pull it, I was just pointing out that I don't think it does what you think it does (sorry).

**Comment by Y-Less** [comment]
Just realised you missed the `TS_` and `RS_` versions of the arrays, you only did the `KS_` one.  The one you did is used in function declarations, the other two are used in function calls.

**Pull request merged**
