### PR TITLE
5.x

### PR DESCRIPTION
**Pull request by Chaprnks**
-added MAX_SINGLE_CALLBACK_HOOKS & changed default to 32

### CODE REVIEW

**Comment by Y-Less** [comment]
Your commit totally broke spacing in the file. Could you please make a version with only the relevant changes?

**Comment by Chaprnks** [comment]
Shoot, I'm sorry! Must be my git client (currently using GitKraken). I'll try redoing the pull request with either the official GitHub Desktop client, or using the Git command line.

**Comment by Southclaws** [comment]
The git client won't be doing that, it's the editor. It's automatic trailing whitespace trimming.

**Comment by Chaprnks** [comment]
Oh, must be my Sublime Text config, I'll check the config settings later today

**Comment by Y-Less** [comment]
@Chaprnks ?

**Pull request closed without merging**
