### PR TITLE
Update y_vehicledata.inc

### PR DESCRIPTION
**Pull request by Dayvison**
Added the flag "Shot" to vehicles that give damage.  
Added info the model top speed and stock function to returns the current speed of vehicle.  

``` pawn
// Current speed of vehicle
printf("%d/%d", Vehicle_Speed(vehicleid), Vehicle_TopSpeed(vehicleid));

```

### CODE REVIEW

**Comment by Dayvison** [comment]
which name to replace `shot` you suggest?

**Comment by Crayder** [comment]
Perhaps something like `HasGun` or something.

**Comment by Misiur** [comment]
How's it coming along?

**Comment by Y-Less** [comment]
Maybe "Armed"?  Looking back, "Weaponised" maybe wasn't the best choice for the ones that don't actually shoot guns.

**Comment by Dayvison** [comment]
Yes, `Armed` is a good, idea,

**Comment by Misiur** [comment]
Sorry for delay, missed that last update

**Pull request merged**
